-
  name: 8
  internal: auto
  css-light: jellybean
  css-dark: rouge
  logo: auto-preview.png
  color: 'f7bd768d'
  themetype: auto
  class: default
- 
  name: 1
  internal: jellybean
  css: jellybean
  logo: jellybean.png
  color: 'A4E0EB'
  themetype: light
  class: default

- 
  name: 6
  internal: taupe
  css: taupe
  logo: taupe.gif
  color: 'f7bd768d'
  themetype: semi
  class: default
-
  name: 7
  internal: rouge
  css: rouge
  logo: rouge.gif
  color: '3c1c1c'
  themetype: dark
  class: default

-
  name: 3
  internal: plain-light
  css: plain-light
  logo: plain_to_light.gif
  color: 'FFFFFF'
  themetype: light
  class: plain

-
  name: 4
  internal: plain-dark
  class: plain
  themetype: dark
  logo: plain_to_dark.gif
  color: '000000'
  css: plain-dark

-
  name: 9
  internal: plain-auto
  css-light: plain-light
  css-dark: plain-dark
  color: '3F3F3F'
  logo: https://logger-diary.strawmelonjuice.com/img/logo/logo_816px.webp
  themetype: auto
  description: 
  class: plain
-
  name: 11
  internal: hellokitten
  color: 'FFB7C5'
  logo: hellokitton.png
  css: hellokittu
  themetype: light
  class: colored
-
  name: 12
  internal: journal
  color: 'EEE1C6'
  css: journal-antique
  logo: journal.gif
  themetype: light
  class: colored
-
  name: 18
  internal: snight
  color: '7289D'
  logo: snight.png
  css: snight
  themetype: dark
  class: colored
-
  name: 14
  internal: pastellia
  color: 'a7cec5'
  logo: pastellia.gif
  css: pastellia
  themetype: semi
  class: colored
-
  name: 21
  internal: pastellia-snight
  color: '7289D'
  logo: https://logger-diary.strawmelonjuice.com/img/logo/logo_816px.webp
  css-light: pastellia
  css-dark: snight
  themetype: auto
  class: colored
-
  name: 13
  internal: aurora
  color: '2a33dc'
  css: aurora.2
  logo: aurora-preview.gif
  themetype: dark
  class: colored
-
  name: 17
  internal: heartbeat
  color: 'pink'
  logo: heartbeat-preview.png
  css: heartbeat
  themetype: light
  class: colored
-
  name: 16
  internal: skyframe
  color: 'a7cec5'
  logo: skyframe.png
  css: mod-framework/skyframe
  themetype: light
  class: modified
-
  name: 20
  internal: strawmelonjuice-auto
  color: 'EEDEAB'
  logo: https://strawmelonjuice.com/assets/img/Strawmelonjuice.webp
  css-dark: strawmelonjuice-dark
  css-light: strawmelonjuice-light
  themetype: auto
  class: strawmelonjuice
-
  name: 15
  internal: strawmelonjuice-light
  color: 'EEDEAB'
  logo: https://strawmelonjuice.com/assets/img/strawmelontheme-flowers.png
  css: strawmelonjuice-light
  themetype: light
  class: strawmelonjuice
-
  name: 19
  internal: strawmelonjuice-dark
  color: '852668'
  logo: https://strawmelonjuice.com/assets/img/strawmelontheme-moons.png
  css: strawmelonjuice-dark
  themetype: light
  class: strawmelonjuice
