# The original language file... ooh.
"code": "en"
1: Welcome
2: the simple digital diary software
3: Made with
4: love
5: Welcome to
6: Home
7: Settings
8:
  1: "Up early"
  2: "Good morning"
  3: "Good afternoon"
  4: "Good evening"
9: News
10: '' # Number 10 is disabled for the default language, as it's probably in the default language already; For translations: 'Content on this page is possibly not translated because it is fetched from static documents.'
11: Contributors
12: That helped creating
13: Want to let something out?
14: Your past entries
15: "Your streak was reset, last time that you logged in was "
16: " days ago."
17: "Daily streak: "
53: "Post your streak celebrations!"
18: When
19: What you wrote
20:	How you felt
21:
  - 'I ate spaghetti'
  - 'I just walked down the stairs... and..'
  - 'I built a cute house in Minecraft today!'
  - 'I just saw a house made of candy, should I try and get a smoll bite?'
  - 'Baked a cake!!!'
  - 'Almost my birthday. Counting down the days...'
  - 'My phone hasn''t worked in five days, so I''m just chillin'''
  - 'A very cute dog'
  - 'I just studied for 4 hours straight??'
  - 'I failed my test'
  - 'Steps goals for today: CHECK!'
22: "What's happening?"
23: "How does this make you feel?"
24: "Write down"
25: 
  1: "Loading past entries..."
  2: "Downloading entry data" #1
  3: "Unpacking entry data" #2
  4: "Creating a table to put the data into" #3
  5: "Organising entry data into table" #4
  6: "Ready to show entries!" #5
26: "Retry"
27: "ON"
28: "OFF"
29: "Focus mode is"
30: "Change"
31: "Logger-Diary Cloud Edition, last updated:"
32: "with commit ID:"
33: "Want to"
34: "go back"
35: "Change your Logger-Diary theme"
36: "Entry-creator settings"
37: "Focus mode"
38: "Long Entries"
39: "Turn off"
40: "Turn on"
41: "Donation button"
42: "Shown"
43: "Hidden"
44: "Hide"
45: "Show"
46: "Account"
47: "Change your Password"
48: "Sign out"
49: "Sign in"
50: # .*.1: Doesn't necessarily need to be translated; is a name.
  1: 
    1: "Sunny meadow in Lavender"
    2: "Default light theme"
  2: 
    1: "Default themes"
    2: "Plain themes"
    3: "Colored themes"
    4: "Modded themes"
    5: "Strawmelonjuice.com themes - on request adapted to LDo"
  3:
    1: "Plain light"
    2: "A plain light theme."
  4: 
    1: "Plain dark"
    2: "A plain dark theme."
  5: "theme"
  6: 
    1: "Taupe"
    2: "Original default theme for Logger-Diary Legacy, revamped for Logger-Diary Online!"
  7: 
    1: "Rouge"
    2: "Default dark theme"
  8: 
    1: "Lavender rouge automatic"
    2: "Can't choose between Summer and Rouge theme? Let your operating system pick!"
  9: 
    1: "Plain automatic"
    2: "Can't choose between the plain themes? Let your operating system pick!"
  10: 
    1: "Preview this theme"
    2: "This theme cannot be previewed."
  11: 
    1: "Hello Kitty"
    2: "Ooh! So pink!"
  12: 
    1: "Journal Antique"
    2: "An old fashion diary."
  13: 
    1: "Space emerald v2.0"
    2: "An intriging theme."
  14: 
    1: "Pastellia"
    2: "Based on the early mar-blog, brings in that fresh pastel color feel."
  15: 
    1: "Strawmelonjuice.com - light"
    2: "The strawmelonjuice.com main website theme."
  16:
    1: "Skyframe"
    2: "A twist on 'Sunny meadow in Lavender'"
  17: 
    1: "Pynk Pulse"
    2: "A brand new theme, for the soft pink lovers!"
  18: 
    1: "Sultry Summernight"
    2: "A theme that might offer your eyes some rest."
  19:
    1: "Strawmelonjuice.com - dark"
    2: "The strawmelonjuice.com main website theme."
  20:
    1: "Strawmelonjuice.com - auto dark/light"
    2: "The strawmelonjuice.com main website theme."
  21:
    1: "Pastelia / Sultry Summernight"
    2: "Automatically switches on light/dark mode of device."
51: "or"
52: "Not yet available"
54:
  1: "Aww, my streak got reset…"
  2: "Getting back on track with my streaks. Back on square one!"
  3: "WOO! A week streak!!"
  4: "One month (30 days) of streak in my pocket!"
  5: "STREAK OF 100 DAYS!"
  6: "One year streak!"
  7: "I joined Logger-Diary Online!"
55: "Username"
56: "Password"
57: "Sign up"
58: "Don't have an account?"
59: "Stay logged in"
60: "Let cookies do the job for you"
61: "Please fill in your credentials to continue"
62: "Already have an account?"
63: "Confirm Password"
64: "About"
65: "Please fill this form to create an account."
66: "more"
67: "less"
68: "Click anywhere outside this section to unfocus."
69:
  1: "Support Logger-Diary Online on Buy me a coffee!"
  2: "Like Logger-Diary? Please support it!"
70: "Language settings"
71:
  'en': "English (default) (current)"
  "nl-nl": "Dutch (Netherlands)"
  "auto": "Automatic (let browser decide)"
72: "Save"
73: "Is a Framework MOD"
74: "In development"
75: "Is BuyMeACoffee not your thing? You can also donate on one of these"
76: "other sites"
"tour":
  -
    1: "Are you new here?"
    2: "Next"
    3: "Skip tour"
    4: "Back"
    5: "Tour"
    6: "Finish tour"
    7: "You finished the tour!"
  - 
    1: "Hello and welcome to LDo! Before you start, might we offer you a quick tour?"
  -
    1: "Okay. See this?"
    2: "This is very much alike what you'll see on the homepage."
    3: "Creating new logger entries"
  -
    1: "Your journey starts at what the big red arrow is pointing at."
    2: "That's where you'll write in. Now of course, you understood "
    3: "that"
    4: " already... so, what's next?"
  -
    1: "This small button with the '⏺️' is what I like to call the feel selector button."
    2: "Click on it to select an emoji that shows how you feel with what you wrote. You can also leave it to be '⏺️' if you don't know what feeling to fill in."
  -
    1: "When you feel like you're ready, hit that submit button and write your entry down!"
    2: "Now it'll show up right here, look!"
  -
    1: "Customisation"
    2: "On the settings screen,"
    3: "you can set various things, like themes (as you might've noticed in the above screenshots), the length of your entries textbox,  FOCUSMODE, and more!"
  -
    1: "Go to homepage"
    2: "Go to settings"
    3: "Set a theme!"
77: "For"
78: "License"
79: "Daily streak"
80: "Hide daily streak"
81: "Focus mode does not work on mobile."
82:
  1: "seconds ago"
  2: "minutes ago"
  3: "hours ago"
  4: "days ago"
  5: "Yesterday"
83: "Long entries might not work well on mobile."